name: Release GitHub
on:
  workflow_dispatch:
jobs:
  publish:
    if: github.repository == 'sgl-project/sglang'
    runs-on: ubuntu-latest
    environment: 'prod'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get version
        id: get_version
        run: |
          version=$(cat python/sglang/version.py | cut -d'"' -f2)
          echo "TAG=v$version" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          name: Release ${{ steps.get_version.outputs.TAG }}
          tag_name: ${{ steps.get_version.outputs.TAG }}
